version: '3.3'

volumes:
  wp_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/data/Wordpress"
  db_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/data/mariadb"
networks:
  inception:
    driver: bridge
services:
 nginx: 
  container_name: nginx
  build: ./requirements/nginx
  networks:
    - inception
  image: nginx:latest
  restart: always
  ports:
    - "443:443"
  env_file:
    - .env
  depends_on:
    - wordpress
  volumes:
    - wp_vol:/var/www/html
 mariadb:
  container_name: mariadb
  networks:
   - inception
  build: ./requirements/MariaDB
  image: mariadb:latest
  restart: always
  env_file:
    - .env
  volumes:
    - db_vol:/var/lib/mysql
 wordpress:
  container_name: wordpress
  networks:
    - inception
  build: ./requirements/WordPress
  image: wordpress:latest
  restart: always
  env_file:
    - .env
  depends_on:
    - mariadb
  volumes:
    - wp_vol:/var/www/html
