version:

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"


services:
  mariadb:
  image: mariadb
  restart: always
  enviroment:
    MYSQL_ROOT_PASSWORD:
  volumes:
    - ./data:/var/lib/mysql
  ports:
    - 3306:3306
