version: '3.3'

services:

  mynginx:
    build: requirements/nginx
    container_name: nginxcontainer
    image: nginximage
    ports:
      - "443:443"


  # mariadb:
  #   container_name: saliha
  #   build:
  #     dockerfile: ./requirements/MariaDB/Dockerfile
  #   image: saliha
  #   restart: always
  #   env_file:
  #     - ./.env
  #   # volumes:
  #   #   - ./data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
